---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-server

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-server
  namespace: echo-server

---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: echo-server
spec:
  selector:
    app: echo-server
  ports:
    - name: echo-server
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: echo-server
  labels:
    app: echo-server
spec:
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      namespace: echo-server
      labels:
        app: echo-server
    spec:
      serviceAccountName: echo-server
      restartPolicy: Always
      containers:
        - name: echo-server
          image: andreswebs/echo-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
