apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: andreswebs/echo-server
      context: "."
      docker:
        dockerfile: Dockerfile
        cacheFrom:
          - golang:alpine
          - alpine:latest

deploy:
  kubectl:
    manifests:
      - k8s/echo-server.yml
